### ISSUE TITLE
Ability to filter calendar events by a participant email

### ISSUE THREAD

**Issue by thomasst** [closeio/nylas#57]
Nylas stores event participants as a JSON object in a MySQL string field. Means we can’t easily filter it to pull events for a specific email address. 

Options:
- Do a %fuzzy% LIKE match and then filter client side (in the Nylas API) for accuracy: bad performance, should not miss any entries though.
- Convert the field into a proper JSON/ARRAY field
- Model it in a relational table

**Comment by jkemp101** [comment]
My first attempt, https://github.com/closeio/nylas/pull/53, at switching the field to a JSON type suggests that might be the easiest option since no tests seemed to fail due to that change. However, that requires upgrading SQLAlchemy which is riskier and caused other tests to fail. I started investigating SQLA issues separately in https://github.com/closeio/nylas/pull/54 but the exact cause of the failure still needs to be figured out. And the SQLA change is somewhat risky so it should be deployed separately and carefully.

**Comment by thomasst** [comment]
Done in https://github.com/closeio/nylas/pull/59
